-- Custom params for the synth (copied into the project's BootTidal.hs by analysis/build_boot.py).
-- With your own boot file:  :script "/absolute/path/to/synth-SC-STD/tidal/params.hs"
-- Keep in sync with docs/params.md, strudel/params.js, ~scstdSpecs in
-- sc/synthdefs/00_modules.scd, and the UI (CLAUDE.md, decision 8).

:{
-- VCO 1
let o1wave   = pF "o1wave"
    o1lvl    = pF "o1lvl"
    o1oct    = pF "o1oct"
    o1fine   = pF "o1fine"
    o1lf     = pF "o1lf"
    o1lfrate = pF "o1lfrate"
    o1kbd    = pF "o1kbd"
-- VCO 2
    o2wave   = pF "o2wave"
    o2lvl    = pF "o2lvl"
    o2oct    = pF "o2oct"
    o2fine   = pF "o2fine"
    o2pw     = pF "o2pw"
    o2pwm    = pF "o2pwm"
    o2sync   = pF "o2sync"
    o2fm     = pF "o2fm"
    o2kbd    = pF "o2kbd"
-- VCO 3
    o3wave   = pF "o3wave"
    o3lvl    = pF "o3lvl"
    o3oct    = pF "o3oct"
    o3fine   = pF "o3fine"
    o3pw     = pF "o3pw"
    o3pwm    = pF "o3pwm"
    o3fm     = pF "o3fm"
    o3kbd    = pF "o3kbd"
-- Analog character
    drift    = pF "drift"
    vspread  = pF "vspread"
-- Noise, ring mod
    nzcol    = pF "nzcol"
    nzlvl    = pF "nzlvl"
    rmlvl    = pF "rmlvl"
    rma      = pF "rma"
    rmb      = pF "rmb"
-- Sample & hold, lag
    shrate   = pF "shrate"
    shsrc    = pF "shsrc"
    shlag    = pF "shlag"
    lagtime  = pF "lagtime"
    lagsrc   = pF "lagsrc"
-- Mono mode
    monomode = pF "monomode"
    glide    = pF "glide"
-- Audio input (preamp + envelope follower)
    inlvl    = pF "inlvl"
    ingain   = pF "ingain"
    efatk    = pF "efatk"
    efrel    = pF "efrel"
-- Electronic switch
    swrate   = pF "swrate"
    swa      = pF "swa"
    swb      = pF "swb"
    swlvl    = pF "swlvl"
-- Mixer / inverter
    mixa     = pF "mixa"
    mixb     = pF "mixb"
    mixalvl  = pF "mixalvl"
    mixblvl  = pF "mixblvl"
-- Patch cables (<source>_<dest>)
    vco1_pitch = pF "vco1_pitch"
    vco1_vcf   = pF "vco1_vcf"
    vco1_pw    = pF "vco1_pw"
    vco1_vca   = pF "vco1_vca"
    vco2_pitch = pF "vco2_pitch"
    vco2_vcf   = pF "vco2_vcf"
    vco2_pw    = pF "vco2_pw"
    vco2_vca   = pF "vco2_vca"
    vco3_pitch = pF "vco3_pitch"
    vco3_vcf   = pF "vco3_vcf"
    vco3_pw    = pF "vco3_pw"
    vco3_vca   = pF "vco3_vca"
    noise_pitch= pF "noise_pitch"
    noise_vcf  = pF "noise_vcf"
    noise_pw   = pF "noise_pw"
    noise_vca  = pF "noise_vca"
    sh_pitch   = pF "sh_pitch"
    sh_vcf     = pF "sh_vcf"
    sh_pw      = pF "sh_pw"
    sh_vca     = pF "sh_vca"
    adsr_pitch = pF "adsr_pitch"
    adsr_pw    = pF "adsr_pw"
    adsr_vca   = pF "adsr_vca"
    ar_pitch   = pF "ar_pitch"
    ar_vcf     = pF "ar_vcf"
    ar_pw      = pF "ar_pw"
    rm_pitch   = pF "rm_pitch"
    rm_vcf     = pF "rm_vcf"
    rm_pw      = pF "rm_pw"
    rm_vca     = pF "rm_vca"
    envf_pitch = pF "envf_pitch"
    envf_vcf   = pF "envf_vcf"
    envf_pw    = pF "envf_pw"
    envf_vca   = pF "envf_vca"
    mix_pitch  = pF "mix_pitch"
    mix_vcf    = pF "mix_vcf"
    mix_pw     = pF "mix_pw"
    mix_vca    = pF "mix_vca"
-- VCF
    vcfcut   = pF "vcfcut"
    vcfres   = pF "vcfres"
    vcfenv   = pF "vcfenv"
    vcfkey   = pF "vcfkey"
    vcfdrive = pF "vcfdrive"
    vcfmodel = pF "vcfmodel"  -- 0 = MoogLadder, 1 = MoogFF
-- VCA
    vcalvl   = pF "vcalvl"
    vcaenv   = pF "vcaenv"
    vcainit  = pF "vcainit"
-- ADSR
    eatk     = pF "eatk"
    edec     = pF "edec"
    esus     = pF "esus"
    erel     = pF "erel"
    ecurve   = pF "ecurve"
-- AR
    aratk    = pF "aratk"
    arrel    = pF "arrel"
-- Spring reverb
    spmix    = pF "spmix"
    spdecay  = pF "spdecay"
    sptone   = pF "sptone"
:}
