"""Builds the project's BootTidal.hs: Tidal's standard boot code + the synth's params.

Why: the VS Code Tidal extension runs ghci from "/" (checked: its working folder), so a boot file
cannot load tidal/params.hs by a relative path, and an absolute path only works on one machine.
So BootTidal.hs is self-contained: it starts Tidal and declares every param itself.
tidal/params.hs stays the source (and is what people with their own boot file `:script`).

Run after changing tidal/params.hs (check_params.py fails until you do):
  .venv/bin/python analysis/build_boot.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

HEADER = """\
-- synth-SC-STD boot file for TidalCycles. GENERATED by analysis/build_boot.py from Tidal's
-- standard BootTidal.hs (Tidal 1.10) and tidal/params.hs: edit those, then run the script.
--
-- The VS Code Tidal extension uses this file automatically when you open this folder.
-- Other editors: point them at this file, or add
--   :script "/absolute/path/to/synth-SC-STD/tidal/params.hs"
-- to your own BootTidal.hs.
--
-- If your ~/.ghci already starts Tidal, Tidal would start twice: see README ("Tidal starts twice").

"""

STANDARD = """\
:set -fno-warn-orphans -Wno-type-defaults -XMultiParamTypeClasses -XOverloadedStrings
:set prompt ""

-- Import all the boot functions and aliases.
import Sound.Tidal.Boot

default (Rational, Integer, Double, Pattern String)

-- Create a Tidal Stream with the default settings.
tidalInst <- mkTidal

-- This orphan instance makes the boot aliases work!
-- It has to go after you define 'tidalInst'.
instance Tidally where tidal = tidalInst

"""

FOOTER = """
:set prompt "tidal> "
:set prompt-cont ""
"""


def params_block() -> str:
    text = (ROOT / "tidal/params.hs").read_text()
    m = re.search(r"^:\{\n.*?^:\}\n", text, re.S | re.M)
    if not m:
        raise SystemExit("no :{ ... :} block in tidal/params.hs")
    return m.group(0)


def expected() -> str:
    return HEADER + STANDARD + "-- synth-SC-STD params (copied from tidal/params.hs)\n" + params_block() + FOOTER


if __name__ == "__main__":
    (ROOT / "BootTidal.hs").write_text(expected())
    print("BootTidal.hs written")
